### ISSUE TITLE
Question : themes

### ISSUE THREAD

**Issue by noraj** [nova1751/hexo-shiki-plugin#2]
With which hexo themes this plugin is compatible?

**Comment by nova1751** [comment]
You can install this plugin to try it out, it is not developed for a specified theme.

**Comment by noraj** [comment]
Yeah but theme developer have to support it right? Do you know themes that use this plugin?
As far as I understand the plugin generates the HTML, but the theme is responsible for the CSS. Or I'm wrong and this plugin works with 99% of themes without them needing to support anything?

**Comment by nova1751** [comment]
> Yeah but theme developer have to support it right? Do you know themes that use this plugin? As far as I understand the plugin generates the HTML, but the theme is responsible for the CSS. Or I'm wrong and this plugin works with 99% of themes without them needing to support anything?

The main job of this plugin is to hijack the rendering of code blocks during the rendering process. So the code block content is not affected by themes. However, you cannot get the theme's original styles for code blocks. That's why I add some extra code to beautify the code blocks, which you can use in other themes.

**Comment by noraj** [comment]
Thanks that amazing, the minimal styling allow this plugin to be universally working for every theme.

I'd just suggest changing the `font-size: 1em;` to `font-size: 100%;` or even not explicitly setting it to not overwrite the chosen size. In my case it resulted in normal small sized text and code being a lot bigger.

**Comment by nova1751** [comment]
Thanks for your advice. However, as I mentioned above, the style for code blocks may vary from theme to theme. So it may not be a good idea to change the css file, as it may work fine in other themes. My suggestion is to customize your own css file. The `css_cdn` option of the plugin config is exposed for that.

**Comment by nova1751** [comment]
Close through #3 #4 .
